# 3.18-era vendor source: relax a few clang -Werror checks that did not exist then.
ccflags-y += -Wno-error=declaration-after-statement
ccflags-y += -Wno-error=unused-variable
ccflags-y += -Wno-error=unused-but-set-variable
ccflags-y += -Wno-error=unused-function
obj-y += imx278mipiraw_Sensor.o
