#
# AXS15260 TDDI touch driver for MTK TPD framework
#

obj-$(CONFIG_TOUCHSCREEN_MTK_AXS) += axs_ts.o

ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
